export { default as Banner } from './Banner'
export { default as BestSellers } from './BestSellers'
export { default as TopRated } from './TopRated'
export { default as Testimonial } from './Testimonial'
export { default as Blog } from './Blog'